name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Build with Gradle
        run: gradle build